import turtle
turtle = turtle.Turtle()
turtle.shape("turtle")
turtle.color('cyan')
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)